### ISSUE TITLE
Possible Google Colab notebook?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [compphoto/BoostingMonocularDepth#1]
Fantastic work!  Thanks for sharing.  Is there any possibility you might consider creating a google colab notebook for the less technically inclined like myself to try this out?

**Comment by k-washi** [comment]
I modified run.py with google colab.  
https://github.com/compphoto/BoostingMonocularDepth/issues/2#issue-909335102

google colab link  
https://colab.research.google.com/drive/12NApv6BAuUTuydDjc6R0dgTzgvRaZ2LW?usp=sharing

**Comment by mahdi139091** [comment]
> I modified run.py with google colab.
> [#2 (comment)](https://github.com/compphoto/BoostingMonocularDepth/issues/2#issue-909335102)
> 
> google colab link
> https://colab.research.google.com/drive/12NApv6BAuUTuydDjc6R0dgTzgvRaZ2LW?usp=sharing

Thanks for the implementation. I will include it in the repo as soon as possible for ease of use.

**Comment by entangledothers** [comment]
Attempting to use the colab notebook with custom images results in following error:

```
Traceback (most recent call last):
  File "run.py", line 499, in <module>
    run(dataset_, option_)
  File "run.py", line 91, in run
    for image_ind, images in enumerate(dataset):
  File "/content/BoostingMonocularDepth/utils.py", line 219, in __getitem__
    return Images(self.rgb_image_dir, self.files, index)
  File "/content/BoostingMonocularDepth/utils.py", line 148, in __init__
    self.rgb_image = read_image(os.path.join(self.root_dir, name))
  File "/content/BoostingMonocularDepth/utils.py", line 27, in read_image
    if img.ndim == 2:
AttributeError: 'NoneType' object has no attribute 'ndim'
```

**Comment by mahdi139091** [comment]
We have released a bug fix today. Please pull the latest version. A Google Colab notebook is also included.

**Comment by kashyappiyush1998** [comment]
> Attempting to use the colab notebook with custom images results in following error:
> 
> ```
> Traceback (most recent call last):
>   File "run.py", line 499, in <module>
>     run(dataset_, option_)
>   File "run.py", line 91, in run
>     for image_ind, images in enumerate(dataset):
>   File "/content/BoostingMonocularDepth/utils.py", line 219, in __getitem__
>     return Images(self.rgb_image_dir, self.files, index)
>   File "/content/BoostingMonocularDepth/utils.py", line 148, in __init__
>     self.rgb_image = read_image(os.path.join(self.root_dir, name))
>   File "/content/BoostingMonocularDepth/utils.py", line 27, in read_image
>     if img.ndim == 2:
> AttributeError: 'NoneType' object has no attribute 'ndim'
> ```

This is the dumbest error ever I received. There is a .ipynb_checkpoint file in inputs just run the command
!rm ./inputs/.ipynb_checkpoint  --> and it will be fine

**Comment by WorldofDepth** [comment]
Apparently .ipynb_checkpoint is a directory, so the command is `!rmdir ./inputs/.ipynb_checkpoint`, I believe.
