### ISSUE TITLE
Mergenet model

### ISSUE THREAD

**Issue by herrartist** [compphoto/BoostingMonocularDepth#13]
I can't download the merge net model from the link of your site.

**Comment by miangoleh** [comment]
Hi. 
Please use the links I provided here #4.

**Comment by WorldofDepth** [comment]
Does the link mentioned here have a permission error, or perhaps it's a bug with the Colab Notebook? When run, it gives this error:
```
Permission denied: https://drive.google.com/uc?id=1cU2y-kMbt0Sf00Ns4CN2oO9qPJ8BensP/
Maybe you need to change permission over 'Anyone with the link'?
mv: cannot stat 'model.pt': No such file or directory
```
Thank you for any help. Terrific project.

**Comment by miangoleh** [comment]
Hi. 
I wasn't able to regenerate the error you are getting. Google colab notebook works fine for me. Please reset your colab runtime settings and set the runtime type to a GPU and run again. I hope it fixes the issue. 
File permission is already "Anyone with the link".

**Comment by miangoleh** [comment]
Closed due to inactivity.
