### ISSUE TITLE
train pix2pix

### ISSUE THREAD

**Issue by GSK666** [compphoto/BoostingMonocularDepth#17]
when i run the train pix2pix code, i get the error No module named 'pix2pix'

**Comment by miangoleh** [comment]
Hi.

Can you please provide me more detailed information? Like what is the execution command you are using, OS etc.

**Comment by GSK666** [comment]
Hi, sorry, i want to train the pix2pix model use my image data, but when i run "python ./pix2pix/train.py --dataroot DATASETDIR --name mergemodeltrain --model pix2pix4depth --no_flip --no_dropout" on the Linux, i get the error: 
-----------------------------------------------------
Traceback (most recent call last):
  File "./pix2pix/train.py", line 22, in <module>
    from options.train_options import TrainOptions
  File "/home/powerop/work/depth_model_code/BoostingMonocularDepth_new/pix2pix/options/train_options.py", line 1, in <module>
    from .base_options import BaseOptions
  File "/home/powerop/work/depth_model_code/BoostingMonocularDepth_new/pix2pix/options/base_options.py", line 3, in <module>
    from pix2pix.util import util
ModuleNotFoundError: No module named 'pix2pix'
-----------------------------------------------------

**Comment by vinthony** [comment]
Try to add the following code at the beginning of the pix2pix/train.py and pix2pix/test.py

```
import os,sys
sys.path.append(os.getcwd())
```

**Comment by miangoleh** [comment]
@GSK666  Please close the issue if the [suggested change above](https://github.com/compphoto/BoostingMonocularDepth/issues/17#issuecomment-886163858) fixed the issue.
