### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes 

### ISSUE THREAD

**Issue by k-washi** [compphoto/BoostingMonocularDepth#2]
!python run.py --Final --data_dir ./inputs --output_dir ./output1 --depthNet 0

Traceback (most recent call last):
  File "run.py", line 498, in <module>
    run(dataset_, option_)
  File "run.py", line 242, in run
    tobemergedto[h1:h2, w1:w2] = np.multiply(tobemergedto[h1:h2, w1:w2], 1 - mask) + np.multiply(merged, mask)
ValueError: operands could not be broadcast together with shapes (672,671) (671,672) 

so, add code in run.py (244 - 246)
```
            h, w = tobemergedto[h1:h2, w1:w2].shape
            mask = cv2.resize(mask, (w, h), interpolation=cv2.INTER_LINEAR)
            merged = cv2.resize(merged, (w, h), interpolation=cv2.INTER_CUBIC)

**Comment by mahdi139091** [comment]
Thanks for reporting the issue. Cab you please provide me the sample image that the error was happening with? I wasn't able to regenerate the error.

**Comment by k-washi** [comment]
An error occurred while processing the directory where the following two images were placed. 
```
import gdown
gdown.download("https://drive.google.com/uc?id=1WjDh_ytbZbDvvhy_nhxUWb5X4cy1POEf", "./sample1.png", quiet=False)
gdown.download("https://drive.google.com/uc?id=14fO24_XOF0qVEjFO1TGbl0iwMiXA4oY8", "./sample2.png", quiet=False)
```

**Comment by mahdi139091** [comment]
Thanks for reporting. I've fixed the bug. Please pull the latest version.
