### ISSUE TITLE
Local Boosting

### ISSUE THREAD

**Issue by kamal-khalaily** [compphoto/BoostingMonocularDepth#20]
Hey,
I understand that the Local Boosting method is done as follows:
-Upsample image if needed
-choose patch size to be receptive field size where 1/3 receptive field size interleave with other patches
-increase the resolution of patches to have enough context 
-discard smooth patches
-sort patches from biggest to smallest
- double estimation on each patch:
High res is fixed at 2*field size
Low res is receptive field size
Then the two patches are resized to 1024x1024 (inference size) not sure about this process TBH
- merge patch with corresponding patch in updated image
The two are scaled to the same size
Pix2pixsize * pix2pixsize
- some trick with polynomials is done since estimations are relative
- apply gaussian mask to make merging look seamless

(1) So, in order to merge two images we resize them to similar fixed sizes?
(2) Are the low and high resolutions for patches correct?
(3) Double-estimation is applied to each patch separately and then with the patch in the base estimate, right?
Thanks in advance!

**Comment by miangoleh** [comment]
Hi.
Just to clarify:
In double estimation each patch is resize to pix2pixsize( = 1024) to be fed to mergenet (1024 is training size of mergenet).

(1) Yes. To be more clear we are merging exactly the same patches (location and size) so they are the same size in any case. We only resize them to mergenet training size for inference. 
(2) Yes. Low res is receptive field and high res is twice that. 
(3) Yes and No. Technically we are using the same mergnet for the double estimation and merging double estimation results for patches to the actual patch location. So given a patch we do a double estimation to generate its depth estimation and then use the mergenet to merge it to the base estimation (It might seem similar to double estimation but it's not).
