### ISSUE TITLE
Ibims1-core-raw Dataset does not exist anymore.

### ISSUE THREAD

**Issue by bayanf** [compphoto/BoostingMonocularDepth#22]
Hey,

I was following the [instructions](https://github.com/compphoto/BoostingMonocularDepth/blob/main/dataset_prepare/mergenet_dataset_prepare.md) for downloading the datasets needed for re-training the merging network, but the [link](https://www.bgu.tum.de/en/lmf/research/datasets/ibims-1/) to the Ibims1-core-raw dataset does not seem to exist anymore.

Thanks.

**Comment by miangoleh** [comment]
Hi. 
Apparently, they have made some changes to their website and the English version of the website is unavailable. 
use the following link for the original webpage:
https://www.asg.ed.tum.de/lmf/ibims1/

and the following to download the dataset:
https://dataserv.ub.tum.de/index.php/s/m1455541

**Comment by flowerdance77** [comment]
hi，I use it to test a image，but the color is different from the example，the near thing is black or purple，the right thing is yellow，can u tell me why？Thanks very much
