### ISSUE TITLE
KeyError: 'inner' 

### ISSUE THREAD

**Issue by mahdis-sa** [compphoto/BoostingMonocularDepth#28]
Can anyone guide me to solve the following error:

I'm trying to run the "test.py" after training by using this command: "python ./pix2pix/test.py --dataroot DATASETDIR --name mergemodeleval --model pix2pix4depth --no_flip --no_dropout" 

but I get this error: 

-------------------------------
creating web directory /content/drive/MyDrive/BMD/net/BoostingMonocularDepth/pix2pix/checkpoints/mergemodeleval/test_latest
OrderedDict():
 OrderedDict()
visual_ret[name]:
 tensor([[[[-0.3939, -0.5247, -0.5284,  ..., -0.5045, -0.5042, -0.4400],
          [-0.5320, -0.5526, -0.5533,  ..., -0.5138, -0.5113, -0.5006],
          [-0.5219, -0.5484, -0.5297,  ..., -0.5128, -0.5091, -0.4998],
          ...,
          [ 0.3818,  0.3915,  0.3934,  ..., -0.4403, -0.4513, -0.4354],
          [ 0.3901,  0.3910,  0.3884,  ..., -0.4387, -0.4599, -0.4186],
          [ 0.3347,  0.3884,  0.3821,  ..., -0.4316, -0.4241, -0.2628]]]],
       device='cuda:0')
visual_ret:
 OrderedDict([('fake_B', tensor([[[[-0.3939, -0.5247, -0.5284,  ..., -0.5045, -0.5042, -0.4400],
          [-0.5320, -0.5526, -0.5533,  ..., -0.5138, -0.5113, -0.5006],
          [-0.5219, -0.5484, -0.5297,  ..., -0.5128, -0.5091, -0.4998],
          ...,
          [ 0.3818,  0.3915,  0.3934,  ..., -0.4403, -0.4513, -0.4354],
          [ 0.3901,  0.3910,  0.3884,  ..., -0.4387, -0.4599, -0.4186],
          [ 0.3347,  0.3884,  0.3821,  ..., -0.4316, -0.4241, -0.2628]]]],
       device='cuda:0'))])
processing (0000)-th image... 00380_colors_&0_0&.png
Traceback (most recent call last):
  File "./pix2pix/test.py", line 71, in <module>
    **inner = visuals['inner']**
**KeyError: 'inner'**

**Comment by mahdis-sa** [comment]
Thank you for the solution. 
So I wonder to know that what is **self.vis.line** in the following lines: 
Actually, I'm trying to plot the loss for each epoch in train.py using this function from "visualizer.py" in the ./pix2pix/utils/ directory but I faced with error with "**self.vis.line**". It's undefined. 
Could you please guide me regarding this issue? 

![Screenshot 2021-09-17 171240](https://user-images.githubusercontent.com/51942105/133806640-2211b24a-8012-4932-aba0-90b1cd239d9a.png)

**Comment by miangoleh** [comment]
We haven't developed these parts of the code. They are borrowed from https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix.
