### ISSUE TITLE
license

### ISSUE THREAD

**Issue by AK391** [compphoto/BoostingMonocularDepth#3]
great work, would it be possible to make a demo for this on https://gradio.app/hub or would that be not allowed due to the license?

**Comment by mahdi139091** [comment]
Thanks for your suggestion. We are considering it and probably will release a version hosted on  https://gradio.app/hub soon.

**Comment by AK391** [comment]
@mahdi139091 great, if you need help let me know, I am also open to making a PR for this

**Comment by yaksoy** [comment]
Hello, person with a completely anonymous blank profile. We will pass on your offer.

Our repository is for research use only, you can not use it yourself on gradio.
