### ISSUE TITLE
Query about calculating actual depth values.

### ISSUE THREAD

**Issue by rohitcmohite** [compphoto/BoostingMonocularDepth#32]
Thats really Awesome Work. The results look really great, Thanks a lot for sharing it.

I tried the code from Git Repo on some other images and the depth maps obtained look really awesome. I had one question though, How can I get actual depth values from the depth map obtained from the model?

**Comment by miangoleh** [comment]
Hi. Thanks for your interest. 
Our model is based on "Monocular" depth estimation models and our merge model is defined to merge ordinal depth. Unfortunately, there is no straightforward way to get the metric depth from monocular depth.
