### ISSUE TITLE
Interpreting results 

### ISSUE THREAD

**Issue by Slazzo** [compphoto/BoostingMonocularDepth#38]
The resulting depth images have more details but also worse depth estimation comparing with other MiDaS implementations, false color and even exr output match poorly with scene.  
![compare](https://user-images.githubusercontent.com/9516880/137568040-da0ee18a-46fe-4fed-88c6-3277dbab8083.jpg)

**Comment by yaksoy** [comment]
Okay. I don't think it's easy to tell which one has worse 'depth' in this example.

**Comment by yaksoy** [comment]
You can still boost Intel ISL Midas or whatever else you want with our method.

**Comment by Slazzo** [comment]
Just to confirm, I wasn't saying is worst, I should be more specific, the one on top fits better to the original scene, the depth spreads linear on reconstruction, it doesn't match but is close to ground truth.
The second doesn't look linear on reconstruction, most of the data is concentrated in planes, doesn't spread uniformly, I was assuming there must be some gamma issue when interpreting the result.

Assumed models trained on same dataset will give very much similar result, I can provide more details about scene reconstruction.
