### ISSUE TITLE
Error Retrieving LeRes weight

### ISSUE THREAD

**Issue by PrinceWang-Cal** [compphoto/BoostingMonocularDepth#41]
While I was trying to get some depth estimation of some of my own images using the `Boostmonoculardepth.ipynb`, I ran into the following error:

<img width="973" alt="Screen Shot 2021-10-29 at 2 57 30 PM" src="https://user-images.githubusercontent.com/44327848/139506237-af8995fd-30e7-48b9-99ee-976ec998b526.png">
<img width="1792" alt="Screen Shot 2021-10-29 at 2 57 42 PM" src="https://user-images.githubusercontent.com/44327848/139506235-80c9c031-b4e0-4c67-a859-34cef12d40e2.png">

It seems like the link https://cloudstor.aarnet.edu.au/plus/s/lTIJF4vrvHCAI31/download hosting the LeRes weights is down. Is there another channel for me to get LeRes weights?

**Comment by miangoleh** [comment]
Hi. I checked now they service is resumed. I hope your problem is fixed too.
