### ISSUE TITLE
Parallel Local Boosting?

### ISSUE THREAD

**Issue by cTatu** [compphoto/BoostingMonocularDepth#45]
Hi
Could the local boosting process (creating, selecting and merging the patches) be done in parallel?

**Comment by miangoleh** [comment]
There is a Sequential nature in creating and then selecting and then merging the patches so they ca1nnot be parallelized. 

But the merging step could be parallelized for independent patches (Patches with no overlap with each other). You have to make sure the logic of merging from biggest patch to smallest patch is still intact.
