### ISSUE TITLE
GPU thresh hold for nvidia A100 ??

### ISSUE THREAD

**Issue by 1kaiser** [compphoto/BoostingMonocularDepth#49]
GPU_threshold = 1600 - 32 # Limit for the GPU (NVIDIA RTX 2080), can be adjusted 

how to find this out for a apecific gpu , does it imapact performance ??

is it the numbers of cuda cores of a gpu ??

**Comment by miangoleh** [comment]
It's the maximum resolution of the image that can be fit on a GPU VRAM. 

Yes, it will affect the performance as it will limit the inference resolution for all our estimations and also changes the effective crop regions.

**Comment by 1kaiser** [comment]
for nvidia A100 what should be GPU_threshold = ???   as memory is 80GB HBM2e
