### ISSUE TITLE
Code section2 error

### ISSUE THREAD

**Issue by Joff1000** [compphoto/BoostingMonocularDepth#52]
Hallo.
I have had this error pop up over the last couple of days while running Colab. I have Factory reset runtime, and terminated previous sessions.
Any help will be much appreciated, thanks in advance, Jonathan

Cloning into 'BoostingMonocularDepth'...
remote: Enumerating objects: 298, done.
remote: Counting objects: 100% (298/298), done.
remote: Compressing objects: 100% (231/231), done.
remote: Total 298 (delta 115), reused 217 (delta 58), pack-reused 0
Receiving objects: 100% (298/298), 55.49 MiB | 3.57 MiB/s, done.
Resolving deltas: 100% (115/115), done.
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/u/0/uc?id=1cU2y-kMbt0Sf00Ns4CN2oO9qPJ8BensP 

mv: cannot stat 'latest_net_G.pth': No such file or directory
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1nqW_Hwj86kslfsXR7EnXpEWdO2csz1cC 

mv: cannot stat 'model.pt': No such file or directory
--2022-02-18 10:13:33--  https://cloudstor.aarnet.edu.au/plus/s/lTIJF4vrvHCAI31/download
Resolving cloudstor.aarnet.edu.au (cloudstor.aarnet.edu.au)... 202.158.207.20
Connecting to cloudstor.aarnet.edu.au (cloudstor.aarnet.edu.au)|202.158.207.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Syntax error in Set-Cookie: 5230042dc1897=jdrh0u0lfe457ebu190haj24n7; path=/plus;; Secure at position 53.
Syntax error in Set-Cookie: oc_sessionPassphrase=tpTKJ%2B%2BsHMKirt%2BEZ4dF2UZOMzNclIR4jgr1AUEX%2BkxgZQbBKzvB9Z2qkVnETdoOSIE66u0s1vRyR%2BzLGfx7GdwhHYmpRShSJmtNYAKETV9YeL9wBN%2FQgPbYLIx364TS; path=/plus;; Secure at position 174.
Length: 530760553 (506M) [application/octet-stream]
Saving to: ‘download’

download            100%[===================>] 506.17M  3.85MB/s    in 2m 3s   

2022-02-18 10:15:38 (4.12 MB/s) - ‘download’ saved [530760553/530760553]

**Comment by WorldofDepth** [comment]
Getting the same error. The google drive file seems to be inaccessible. But you can replace that link (the first google drive link in the code block) with the direct one [https://sfu.ca/~yagiz/CVPR21/latest_net_G.pth] and that works for me at the moment.

**Comment by Joff1000** [comment]
> Getting the same error. The google drive file seems to be inaccessible. But you can replace that link (the first google drive link in the code block) with the direct one [https://sfu.ca/~yagiz/CVPR21/latest_net_G.pth] and that works for me at the moment.

Thanks for the help.
Do you have the link to replace the second error as well? This will be for the model.pt file

**Comment by WorldofDepth** [comment]
> Do you have the link to replace the second error as well? This will be for the model.pt file

Look on the MiDaS GitHub page and there should be an alternate link for that v2.1 weights file.

**Comment by sebastian-dille** [comment]
Hi @Joff1000,
the issue seems to be the high amount of downloads we've seen recently. Unfortunately, Google Drive automatically limits the access. However, as WorldofDepth pointed out, the second link should work fine.

The same seems to be the case for the original MiDaS weights (2nd link) that we do not host ourselves. The authors provide a link on their GitHub page: https://github.com/AlexeyAB/MiDaS/releases/download/midas_dpt/midas_v21-f6b98070.pt. Please note that this file has to be renamed to 'model.pt' after download to correctly work with our architecture.

**Comment by miangoleh** [comment]
I have updated our Colab with new links.
