### ISSUE TITLE
Temporal inconsistency on image sequences

### ISSUE THREAD

**Issue by semel1** [compphoto/BoostingMonocularDepth#53]
The results look awesome. However the result of processing image sequence from video introduces noticeable temporal inconsistency.
Any plan to implement some solution to restore  temporal consistency, or may be you can suggest any work around to solve that?

**Comment by miangoleh** [comment]
Hi. The inconsistency is inherent from the base networks we use in this repo which are not designed for video depth estimation. 
A simple solution would be using our [BoostYourOwnDepth](https://github.com/compphoto/BoostYourOwnDepth). You can generate base estimates from any consistent video depth estimation method and merge it with details from any other MDE method (midas v3 or leres) to get a much better temporal consistency.

**Comment by semel1** [comment]
Thanks a lot for your prompt response. What method would you suggest for "consistent video depth estimation method"?

**Comment by miangoleh** [comment]
It seems to be a research problem of its own, and I am not aware of a solution.

**Comment by longyangqi** [comment]
> Thanks a lot for your prompt response. What method would you suggest for "consistent video depth estimation method"? Unfortunately [BoostYourOwnDepth](https://github.com/compphoto/BoostYourOwnDepth) doesn't solve the problem. It pulls out not only details but also all existing flickering. Top row from the left: Original video, Heavy Edited Consistent Depth Estimation https://github.com/yu-li/TCMonoDepth , Leres . Bottom row from the left: Midas3, "Boosted Depth": Low-res: Consistent Depth Estimation, High-res: Leres, "Boosted Depth": Low-res: Consistent Depth Estimation, High-res: Midas
> 
>  comparesement.mp4

Hi，do you have a solution for consistent high-resolution video depth estimation now?
