### ISSUE TITLE
Issue max res 720 * 1280 ?

### ISSUE THREAD

**Issue by StevenLi-phoenix** [compphoto/BoostingMonocularDepth#55]
I am running the LeRes and with input (3024, 5376, 3)
It tried to downscale by factor of 0.23809523809523808 and result in depthmap output of 720 * 1280
Is this any option that i can adjust to match the original size?

**Comment by StevenLi-phoenix** [comment]
device: cuda
Namespace(Final=True, R0=False, R20=False, colorize_results=False, data_dir='/content/inputs', depthNet=2, max_res=inf, net_receptive_field_size=None, output_dir='/content/drive/MyDrive/outputs_leres/', output_resolution=1, pix2pixsize=1024, savepatchs=0, savewholeest=0)
----------------- Options ---------------
                    Final: True                          	[default: False]
                       R0: False                         
                      R20: False                         
             aspect_ratio: 1.0                           
               batch_size: 1                             
          checkpoints_dir: ./pix2pix/checkpoints         
         colorize_results: False                         
                crop_size: 672                           
                 data_dir: /content/inputs               	[default: None]
                 dataroot: None                          
             dataset_mode: depthmerge                    
                 depthNet: 2                             	[default: None]
                direction: AtoB                          
          display_winsize: 256                           
                    epoch: latest                        
                     eval: False                         
            generatevideo: None                          
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 2                             
                  isTrain: False                         	[default: None]
                load_iter: 0                             	[default: 0]
                load_size: 672                           
         max_dataset_size: 10000                         
                  max_res: inf                           
                    model: pix2pix4depth                 
               n_layers_D: 3                             
                     name: void                          
                      ndf: 64                            
                     netD: basic                         
                     netG: unet_1024                     
 net_receptive_field_size: None                          
                      ngf: 64                            
               no_dropout: False                         
                  no_flip: False                         
                     norm: none                          
                 num_test: 50                            
              num_threads: 4                             
               output_dir: /content/drive/MyDrive/outputs_leres/	[default: None]
                output_nc: 1                             
        output_resolution: None                          
                    phase: test                          
              pix2pixsize: None                          
               preprocess: resize_and_crop               
                savecrops: None                          
             savewholeest: None                          
           serial_batches: False                         
                   suffix:                               
                  verbose: False                         
----------------- End -------------------
initialize network with normal
loading the model from ./pix2pix/checkpoints/mergemodel/latest_net_G.pth
start processing
processing image 0 : 0
	 wholeImage being processed in : 2688
Adjust factor is: 1.0
Selecting patchs ...
Target resolution:  (3024, 5376, 3)
Dynamicly change merged-in resolution; scale: 0.23809523809523808
	 Resulted depthmap res will be : (720, 1280)
patchs to process: 55
	 processing patch 0 | [  0   0 693 693]
	 processing patch 1 | [ 80   0 693 693]
	 processing patch 2 | [160   0 693 693]

**Comment by StevenLi-phoenix** [comment]
I mean actually using the model to predict the result. Not just using resize.
Any suggestions?

**Comment by miangoleh** [comment]
Can you share the command you use to run the model?

**Comment by StevenLi-phoenix** [comment]
!python run.py --Final --data_dir /content/inputs --output_dir  /content/outputs_leres/ --depthNet 2

May I need to add specific parameter that I need to add?

**Comment by StevenLi-phoenix** [comment]
ok.
I think understand what's happening.

The model is processing the image in it input resolution and to avoid too large output, it automatically resize the image after processing. 

am i right?

**Comment by StevenLi-phoenix** [comment]
Maybe there is a max resolution limit? I definitely uploaded a super high resolution image
This one: (from [https://kids.nationalgeographic.com/geography/states/article/new-york](https://kids.nationalgeographic.com/geography/states/article/new-york))
![new-york-statue-of-liberty_16x9](https://user-images.githubusercontent.com/75846119/176663623-870370df-dd64-4b63-9ebc-f3ff92fc745a.jpg)
size: 3072 × 1728

Thank you for your help. I appreciate it very much.
