### ISSUE TITLE
License of output images

### ISSUE THREAD

**Issue by neverix** [compphoto/BoostingMonocularDepth#57]
Hello,

Thank you for building this model. Is the licensing fine with running BMD on an image dataset and distributing resulting depths?

**Comment by miangoleh** [comment]
Hi

Please refere to our our license file :
https://github.com/compphoto/BoostingMonocularDepth/blob/main/LICENSE

Any commercial use of our repo and models is prohibited while academic use is encouraged.

**Comment by neverix** [comment]
I see, thank you!
