### ISSUE TITLE
Unable to download mergenet model weights

### ISSUE THREAD

**Issue by SunilSrivatsav9** [compphoto/BoostingMonocularDepth#61]
Link is not working ....
Can you please check it

**Comment by miangoleh** [comment]
Hi. The link works for me. But if it still is not working for you use the following alternative link:
https://drive.google.com/u/0/uc?id=1cU2y-kMbt0Sf00Ns4CN2oO9qPJ8BensP&export=download

**Comment by SunilSrivatsav9** [comment]
Thank you so much it worked !!!!!!!!
