### ISSUE TITLE
Why does NAN appear in the model inference process

### ISSUE THREAD

**Issue by Jeremy8080** [compphoto/BoostingMonocularDepth#65]
(BoostingMonocularDepth) PS C:\Users\xxx\Desktop\BoostingMonocularDepth-main> python run.py --Final --data_dir ./inputs --output_dir ./output --depthNet 2
device: cuda
Namespace(Final=True, R0=False, R20=False, colorize_results=False, data_dir='./inputs', depthNet=2, max_res=inf, net_receptive_field_size=None, output_dir='./output', output_resolution=1, pix2pixsize=1024, savepatchs=0, savewholeest=0)
----------------- Options ---------------
                    Final: True                                 [default: False]
                       R0: False
                      R20: False
             aspect_ratio: 1.0
               batch_size: 1
          checkpoints_dir: ./pix2pix/checkpoints
         colorize_results: False
                crop_size: 672
                 data_dir: ./inputs                             [default: None]
                 dataroot: None
             dataset_mode: depthmerge
                 depthNet: 2                                    [default: None]
                direction: AtoB
          display_winsize: 256
                    epoch: latest
                     eval: False
            generatevideo: None
                  gpu_ids: 0
                init_gain: 0.02
                init_type: normal
                 input_nc: 2
                  isTrain: False                                [default: None]
                load_iter: 0                                    [default: 0]
                load_size: 672
         max_dataset_size: 10000
                  max_res: inf
                    model: pix2pix4depth
               n_layers_D: 3
                     name: void
                      ndf: 64
                     netD: basic
                     netG: unet_1024
 net_receptive_field_size: None
                      ngf: 64
               no_dropout: False
                  no_flip: False
                     norm: none
                 num_test: 50
              num_threads: 4
               output_dir: ./output                             [default: None]
                output_nc: 1
        output_resolution: None
                    phase: test
              pix2pixsize: None
               preprocess: resize_and_crop
                savecrops: None
             savewholeest: None
           serial_batches: False
                   suffix:
                  verbose: False
----------------- End -------------------
C:\Users\xxx\AppData\Local\anaconda3\envs\BoostingMonocularDepth\lib\site-packages\torch\cuda\__init__.py:125: UserWarning: 
NVIDIA GeForce RTX 3080 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
initialize network with normal
loading the model from ./pix2pix/checkpoints/mergemodel\latest_net_G.pth
start processing
processing image 0 : Visspec
         wholeImage being processed in : 1120
Adjust factor is: 3.474264705882353
Selecting patchs ...
Target resolution:  (7782, 7782, 3)
Dynamicly change merged-in resolution; scale: 0.07388846054998716
         Resulted depthmap res will be : (575, 575)
patchs to process: 196
         processing patch 0 | [ 21  46 525 525]
         processing patch 1 | [  4  54 509 509]
         processing patch 2 | [ 20  95 476 476]
         processing patch 3 | [  4  53 460 460]
         processing patch 4 | [  4  78 460 460]
         processing patch 5 | [  4 103 460 460]
C:\Users\xxx\AppData\Local\anaconda3\envs\BoostingMonocularDepth\lib\site-packages\numpy\lib\polynomial.py:630: RuntimeWarning: invalid value encountered in true_divide
  lhs /= scale
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  5 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
Traceback (most recent call last):
  File "run.py", line 595, in <module>
    run(dataset_, option_)
  File "run.py", line 276, in run
    p_coef = np.polyfit(mapped.reshape(-1), patch_whole_estimate_base.reshape(-1), deg=1)
  File "<__array_function__ internals>", line 6, in polyfit
  File "C:\Users\xxx\AppData\Local\anaconda3\envs\BoostingMonocularDepth\lib\site-packages\numpy\lib\polynomial.py", line 631, in polyfit
    c, resids, rank, s = lstsq(lhs, rhs, rcond)
  File "<__array_function__ internals>", line 6, in lstsq
  File "C:\Users\xxx\AppData\Local\anaconda3\envs\BoostingMonocularDepth\lib\site-packages\numpy\linalg\linalg.py", line 2268, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
  File "C:\Users\xxx\AppData\Local\anaconda3\envs\BoostingMonocularDepth\lib\site-packages\numpy\linalg\linalg.py", line 109, in _raise_linalgerror_lstsq
    raise LinAlgError("SVD did not converge in Linear Least Squares")
numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares

**Comment by miangoleh** [comment]
Sorry for the late reply. I need the input example that causes this issue to be able to help you with this.
