### ISSUE TITLE
LeRes weights download link is not working

### ISSUE THREAD

**Issue by ivanlen** [compphoto/BoostingMonocularDepth#67]
The link `https://cloudstor.aarnet.edu.au/plus/s/lTIJF4vrvHCAI31/download` is not working. Any alternative?

Also `https://sfu.ca/~yagiz/CVPR21/latest_net_G.pth` is not working.

**Comment by miangoleh** [comment]
You can take a look at their repo. https://github.com/aim-uofa/AdelaiDepth/tree/main/LeReS
