### ISSUE TITLE
no NVIDIA driver found error

### ISSUE THREAD

**Issue by Katydidonline** [compphoto/BoostingMonocularDepth#72]
Hello,
I am trying to run Tiled ZoeDepth to get a depth map and I keep getting an error that says no NVIDIA driver was found. 

I do have a NVIDIA GeForce RTX 2060 with a game ready driver version 551.76. I tried updating the driver and restating my computer with no change. Any idea what I am doing wrong?

Thank you!

**Comment by miangoleh** [comment]
Please help me to understand first. We do not have a Tiled version of Zoedepth in our repo. Are you trying to implement and use Zoedepth as base depth estimation in our framework?

**Comment by miangoleh** [comment]
Closed due to inactivity.
