### ISSUE TITLE
Error: Attribute error

### ISSUE THREAD

**Issue by herrartist** [compphoto/BoostingMonocularDepth#76]
I get this error:
Attribute error: module 'torch_C' has no attribute ' cuda_setDevice'

I am working on Windows 10 and with this graphic card: NVIDA GeoForce RTX 3080 Ti

What can I do?

**Comment by miangoleh** [comment]
You can use the same environment as explained in [here](https://github.com/compphoto/SIDepth/issues/2). 
You only need to install matplotlib in it as well. 
```
conda activate newsidepthenv 
pip install matplotlib
```

**Comment by miangoleh** [comment]
And as a general recommendation, the SSI model introduced in our [new work](https://github.com/compphoto/sidepth) has a better performance compared to the models used as baseline in this repo in generating intricate details. It also uses the same boosting framework.

**Comment by miangoleh** [comment]
Closed due to inactivity.
