### ISSUE TITLE
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

### ISSUE THREAD

**Issue by arasharchor** [compphoto/BoostingMonocularDepth#8]
you have mentioned the code works properly with pytorch <=1.8 as as well, but torch.utils.ffi has been since 0.4.0 depreciated. In the requirements.txt, one sees pytorch==1.2

with torch 0.4.1, the following error occurs:
AttributeError: module 'torch' has no attribute 'ops'
or 
File "./structuredrl/models/syncbn/modules/functional/_syncbn/_ext/syncbn/__init__.py", line 3, in <module>
    from ._syncbn import lib as _lib, ffi as _ffi
ImportError: No module named 'modules.functional._syncbn._ext.syncbn._syncbn'

**Comment by miangoleh** [comment]
Hi. 

That sentence("works for torch<1.8") only refers to our Mergnet model alone in case one wants to apply our method to their own depth estimation base network.
 
Midas-v2 and SGR have their own requirements described in README.md (You have to use different environments for each of them). requirement.txt is for our gradio demo(which has not yet released). Please discard it and follow the instructions in README.md.

**Comment by miangoleh** [comment]
Closed due to inactivity
