### ISSUE TITLE
Is it possible to obtain distance in meters?

### ISSUE THREAD

**Issue by LulaSan** [compphoto/BoostingMonocularDepth#9]
Hi, I was wondering if the output is only a disparity map or it is possible to obtain a metric depth map using this network.
Thank you in advance!

**Comment by miangoleh** [comment]
Hi. 
We do not train or propose a depth estimation model. we boost already existing monocular depth models which output ordinal depth with our method.  
Also, our merge model is trained for ordinal depth and is not aimed or tested for metric depth.

**Comment by kwea123** [comment]
Which means it is better at distinguishing which pixels are closer, which are farther with more details than previous methods. But it doesn't give any reliable metric depth, ie. if you backproject the disparity back to 3d points, it is not going to look well, if I understand that correctly.

**Comment by miangoleh** [comment]
Yes, It's correct

**Comment by ucalyptus** [comment]
Can future works / or existing works (since I live under a rock) find metric depth from ordinal depth?

**Comment by miangoleh** [comment]
That's a research question. I don't have the answer now.

**Comment by miangoleh** [comment]
Closed due to inactivity.
